services:
  - type: web
    name: notivo1-backend
    runtime: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
